/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BeachServiceForm: typeof import('./src/components/BeachServiceForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    FloatLabel: (typeof import('./src/components/FloatIcon.vue'))['default ']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/user/LoginForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    PricesForm: typeof import('./src/components/PricesForm.vue')['default']
    PricesList: typeof import('./src/components/PricesList.vue')['default']
    ReportTable: typeof import('./src/components/ReportTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: (typeof import('primevue/row'))['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    VoucherForm: typeof import('./src/components/VoucherForm.vue')['default']
    VoucherList: typeof import('./src/components/VoucherList.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
